service:
  name: meetup

provider:
  name: scaleway
  runtime: node10
  # scwToken:
  # scwOrganization: 

plugins:
  - serverless-scaleway-functions

package:
  include:
    - dogs

functions:
  demo:
    handler: demo/index.js

  apollo-lambda:
    handler: dogs/index.handler
    env:
      DB_HOST: 
      DB_USER: 
      DB_PASSWORD:
      DB_NAME:

