service:
  name: meetup

provider:
  name: scaleway
  runtime: node10

custom:
  containers:
    apollo-container:
      directory: .
      env:
        DB_HOST: 
        DB_USER: 
        DB_PASSWORD:
        DB_NAME:


plugins:
  - serverless-scaleway-functions

package:
  include:
    - dogs
    - demo

functions:
  demo:
    handler: demo/index.handler

  apollo-lambda:
    handler: dogs/index.handler
    env:
      DB_HOST: 
      DB_USER:
      DB_PASSWORD:
      DB_NAME: 
